#Crei un Tag (es. git tag -a v1.0.0 -m "Versione 1.0.0") e lo invii a GitHub (git push origin v1.0.0).
name: Release Creation

on:
  push:
    tags:
      - 'v*' # Si attiva quando crei un tag che inizia con v (es. v1.0.0)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update Manifest
        run: node ./scripts/update-manifest.js ${{ github.ref_name }}

      # Step opzionale: se hai file YAML da compilare
      # - name: Build Compendiums
      #   run: npm run build

      - name: Create Versioned Zip
        run: |
          # Es: warhero-v1.0.1.zip
          zip -r ./fvtt-warhero-${{ github.ref_name }}.zip . -x ".git/*" ".github/*" "node_modules/*" "scripts/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            system.json
            fvtt-warhero-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
